#!/bin/bash
# deploy-companion.sh — Deploy companion tools to all WaveTerm SSH targets
# Pushes scripts to ~/.waveterm/companion/ on each remote host.
# Idempotent — safe to run repeatedly.
#
# Usage: bash deploy-companion.sh [connection-name]
#   No args: deploy to all connections
#   With arg: deploy to specific connection only

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REMOTE_DIR=".waveterm/companion"
REMOTE_ALIASES=".waveterm/companion/aliases.sh"

# Scripts to deploy (only the portable bash ones, not PowerShell)
SCRIPTS=(
    "ctx-launch.sh"
    "companion.sh"
    "remote-browse.sh"
)

# Alias file content (generated, not copied — uses remote paths)
generate_aliases() {
    cat << 'ALIASES_EOF'
# WaveTerm Companion Aliases — auto-generated by deploy-companion.sh
# Sourced via cmd:initscript.bash in WaveTerm connections.json

_WC="$HOME/.waveterm/companion"

if [[ -n "$WAVETERM" ]]; then
    alias cc="bash $_WC/companion.sh"
    alias cbtop="bash $_WC/ctx-launch.sh btop"
    alias clg="bash $_WC/ctx-launch.sh lazygit"
    alias chtop="bash $_WC/ctx-launch.sh htop"
    alias ctig="bash $_WC/ctx-launch.sh tig"
    alias ck9s="bash $_WC/ctx-launch.sh k9s"
    alias cnvtop="bash $_WC/ctx-launch.sh nvtop"
    alias cdust="bash $_WC/ctx-launch.sh dust"
    alias cncdu="bash $_WC/ctx-launch.sh ncdu"
    alias cmc="bash $_WC/ctx-launch.sh mc"
    alias cdocker="bash $_WC/ctx-launch.sh docker"
    alias cgpu="bash $_WC/ctx-launch.sh gpu"
    alias clogs="bash $_WC/ctx-launch.sh logs"
    alias cports="bash $_WC/ctx-launch.sh ports"
fi
ALIASES_EOF
}

# Connection map: name -> "user@host -p port -i keyfile"
declare -A CONNECTIONS
CONNECTIONS[phenix@dgx]="phenix@120.28.138.55 -p 2442 -i $HOME/.ssh/id_ed25519"
CONNECTIONS[alaa@dgx1]="alaa@120.28.138.55 -p 2442 -i $HOME/.ssh/id_ed25519_alaa"
CONNECTIONS[root@mce-new]="root@152.42.191.40 -p 2222 -i $HOME/.ssh/id_ed25519_alaa"
CONNECTIONS[alaa@warpgate]="alaa@warp.nulled.ai -p 2222 -i $HOME/.ssh/id_ed25519_alaa"

ESC='\033'
GREEN="${ESC}[32m"
RED="${ESC}[31m"
YELLOW="${ESC}[33m"
CYAN="${ESC}[36m"
DIM="${ESC}[2m"
RESET="${ESC}[0m"

deploy_to() {
    local name="$1"
    local ssh_args="$2"

    echo -e "${CYAN}Deploying to ${name}...${RESET}"

    # Create remote directory
    if ! ssh -o ConnectTimeout=8 -o BatchMode=yes $ssh_args "mkdir -p ~/$REMOTE_DIR" 2>/dev/null; then
        echo -e "  ${RED}FAIL${RESET} — SSH connection failed"
        return 1
    fi

    # Copy scripts
    local scp_target="${ssh_args%% *}:~/$REMOTE_DIR/"
    local scp_port=""
    if [[ "$ssh_args" =~ -p\ ([0-9]+) ]]; then
        scp_port="-P ${BASH_REMATCH[1]}"
    fi
    local scp_key=""
    if [[ "$ssh_args" =~ -i\ ([^ ]+) ]]; then
        scp_key="-i ${BASH_REMATCH[1]}"
    fi

    for script in "${SCRIPTS[@]}"; do
        if scp -o BatchMode=yes $scp_port $scp_key "$SCRIPT_DIR/$script" "$scp_target" 2>/dev/null; then
            echo -e "  ${GREEN}OK${RESET} $script"
        else
            echo -e "  ${RED}FAIL${RESET} $script"
        fi
    done

    # Generate and deploy aliases file
    generate_aliases | ssh -o BatchMode=yes $ssh_args "cat > ~/$REMOTE_ALIASES && chmod +x ~/$REMOTE_DIR/*.sh" 2>/dev/null
    if [[ $? -eq 0 ]]; then
        echo -e "  ${GREEN}OK${RESET} aliases.sh (generated)"
    else
        echo -e "  ${RED}FAIL${RESET} aliases.sh"
    fi

    echo -e "  ${DIM}Done${RESET}"
}

# Filter by argument or deploy to all
TARGET="${1:-}"

if [[ -n "$TARGET" ]]; then
    if [[ -n "${CONNECTIONS[$TARGET]}" ]]; then
        deploy_to "$TARGET" "${CONNECTIONS[$TARGET]}"
    else
        echo -e "${RED}Unknown connection: $TARGET${RESET}"
        echo "Available: ${!CONNECTIONS[*]}"
        exit 1
    fi
else
    echo -e "${CYAN}Deploying companion tools to all connections${RESET}"
    echo ""
    for name in "${!CONNECTIONS[@]}"; do
        deploy_to "$name" "${CONNECTIONS[$name]}"
        echo ""
    done
fi

echo ""
echo -e "${GREEN}Deployment complete.${RESET}"
echo -e "${DIM}To activate, add to each connection in connections.json:${RESET}"
echo -e "${DIM}  \"cmd:initscript.bash\": \"~/.waveterm/companion/aliases.sh\"${RESET}"
echo -e "${DIM}Or set globally in settings.json:${RESET}"
echo -e "${DIM}  \"cmd:initscript.bash\": \"~/.waveterm/companion/aliases.sh\"${RESET}"
